### ISSUE TITLE
Saving interface object server fails and leaves empty XML file (Windows 10 64-Bit)

### ISSUE THREAD

**Issue by nanosonde** [calimero-project/calimero-device#1]
I am using the calimero-server on my Windows 10 with a TPUART connection.
Everything seem to work fine except when it comes to saving and load of the interface object server data.

When closing the calimero-server I get the following error:

```
10:36:43:267 DEBUG calimero.device.knx-server - saving interface object server to file:///C:/Users/User/Documents/calimero-server/knx-server-ios.xml
10:36:43:267 INFO calimero.server.knx-server - knx-server control endpoint COM5 closed
10:36:43:267 TRACE calimero.xml - using StaX XMLStreamWriter com.sun.xml.internal.stream.writers.XMLStreamWriterImpl
10:36:43:267 ERROR calimero.device.knx-server - saving interface object server
tuwien.auto.calimero.xml.KNXMLException: writeStartDocument
        at tuwien.auto.calimero.xml.XmlStreamWriterProxy.writeStartDocument(XmlStreamWriterProxy.java:341)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer$XmlSerializer.save(InterfaceObjectServer.java:860)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer$XmlSerializer.saveInterfaceObjects(InterfaceObjectServer.java:846)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer.saveInterfaceObjects(InterfaceObjectServer.java:256)
        at tuwien.auto.calimero.device.BaseKnxDevice.saveIos(BaseKnxDevice.java:557)
        at tuwien.auto.calimero.device.BaseKnxDevice.close(BaseKnxDevice.java:544)
        at tuwien.auto.calimero.server.knxnetip.KNXnetIPServer.shutdown(KNXnetIPServer.java:776)
        at tuwien.auto.calimero.server.Launcher.close(Launcher.java:672)
        at tuwien.auto.calimero.server.Launcher.quit(Launcher.java:664)
        at tuwien.auto.calimero.server.Launcher.run(Launcher.java:641)
        at tuwien.auto.calimero.server.Launcher.main(Launcher.java:609)
Caused by: javax.xml.stream.XMLStreamException: Underlying stream encoding 'Cp1252' and input paramter for writeStartDocument() method 'UTF-8' do not match.
        at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.verifyEncoding(XMLStreamWriterImpl.java:1246)
        at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeStartDocument(XMLStreamWriterImpl.java:1184)
        at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeStartDocument(XMLStreamWriterImpl.java:1167)
        at tuwien.auto.calimero.xml.XmlStreamWriterProxy.writeStartDocument(XmlStreamWriterProxy.java:338)
        ... 10 more
10:36:43:283 DEBUG calimero.device.knx-server - saving device memory to C:\Users\User\Documents\calimero-server\knx-server-ios.mem
```

This leaves an empty "knx-server-ios.xml" file with 0 bytes.

On next startup the calimero-server fails while trying to read the IOS data:

```
10:56:09:564 DEBUG calimero.device.knx-server - loading interface object server from file:///C:/Users/User/Documents/calimero-server/knx-server-ios.xml
10:56:09:576 TRACE calimero.xml - resolve file:///C:/Users/User/Documents/calimero-server/knx-server-ios.xml
10:56:09:580 TRACE calimero.xml - using StaX XMLStreamReader com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl
Exception in thread "main" tuwien.auto.calimero.xml.KNXMLException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
        at tuwien.auto.calimero.xml.XmlStreamReaderProxy.wrapped(XmlStreamReaderProxy.java:204)
        at tuwien.auto.calimero.xml.XmlStreamReaderProxy.nextTag(XmlStreamReaderProxy.java:98)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer$XmlSerializer.load(InterfaceObjectServer.java:821)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer$XmlSerializer.loadInterfaceObjects(InterfaceObjectServer.java:802)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer.load(InterfaceObjectServer.java:221)
        at tuwien.auto.calimero.device.ios.InterfaceObjectServer.loadInterfaceObjects(InterfaceObjectServer.java:207)
        at tuwien.auto.calimero.device.BaseKnxDevice.loadIosFromResource(BaseKnxDevice.java:685)
        at tuwien.auto.calimero.device.BaseKnxDevice.initIos(BaseKnxDevice.java:649)
        at tuwien.auto.calimero.device.BaseKnxDevice.<init>(BaseKnxDevice.java:242)
        at tuwien.auto.calimero.server.knxnetip.KNXnetIPServer.<init>(KNXnetIPServer.java:364)
        at tuwien.auto.calimero.server.Launcher.<init>(Launcher.java:621)
        at tuwien.auto.calimero.server.Launcher.main(Launcher.java:606)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.nextTag(XMLStreamReaderImpl.java:1346)
        ... 11 more
```

Removing the empty knx-server-ios.xml before starting the server makes the server start properly again.

**Comment by nanosonde** [comment]
Ah, thanks for the hint.

Now it is able to generate a file which is not empty.

However, when restarting the server, I get:
```
16:39:45:644 TRACE calimero.xml - resolve server-config.xml
16:39:45:691 TRACE calimero.xml - using StaX XMLStreamReader com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl
16:39:46:058 TRACE calimero.xml - resolve jar:file:/C:/Users/User/Documents/calimero-server/calimero-core-2.5-M1.jar!/properties.xml
16:39:46:058 TRACE calimero.xml - using StaX XMLStreamReader com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl
16:39:46:078 DEBUG calimero.device.knx-server - loading interface object server from file:///C:/Users/User/Documents/calimero-server/knx-server-ios.xml
16:39:46:080 TRACE calimero.xml - resolve file:///C:/Users/User/Documents/calimero-server/knx-server-ios.xml
16:39:46:080 INFO calimero.device.knx-server - could not open file:///C:/Users/User/Documents/calimero-server/knx-server-ios.xml, create resource on closing device (C:\Users\User\Documents\calimero-server\knx-server-ios.xml (Das System kann die angegebene Datei nicht finden))
```

Is there still an issue? The file is definitely there: C:\Users\User\Documents\calimero-server\knx-server-ios.xml
